# Write a Python Program to Add Two Matrices?

In [1]:
# Program to add two matrices using nested loop

X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

# iterate through rows
for i in range(len(X)):
   # iterate through columns
   for j in range(len(X[0])):
      result[i][j] = X[i][j] + Y[i][j]

for r in result:
   print(r)

[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


# Write a Python Program to Multiply Two Matrices?

In [2]:
import numpy as np

# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]

# convert lists to numpy arrays
X = np.array(X)
Y = np.array(Y)

# result is 3x4
result = X.dot(Y)

print(result)

[[114 160  60  27]
 [ 74  97  73  14]
 [119 157 112  23]]


# Write a Python Program to Transpose a Matrix?

In [3]:
# Define an original 3x2 matrix
X = [[1, 2],
     [4, 5],
     [3, 6]]

# Create an empty 2x3 matrix for storing the result
result = [[0, 0, 0],
          [0, 0, 0]]

# Iterate through rows
for i in range(len(X)):
   # Iterate through columns
   for j in range(len(X[0])):
       # Assign the element at row i and column j of X
       # To the element at row j and column i of result
       result[j][i] = X[i][j]

# Print the transposed matrix
for r in result:
   print(r)

[1, 4, 3]
[2, 5, 6]


# Write a Python Program to Sort Words in Alphabetic Order?

In [5]:


# Program to sort words in alphabetic order using sorted()

# Define an original string
my_str = "Hello this Is an Example With cased letters"

# Split the string into a list of words
words = my_str.split()

# Convert each word to lowercase
words = [word.lower() for word in words]

# Use sorted() function to sort the words
sorted_words = sorted(words)

# Print the sorted words
print("The sorted words are:")
for word in sorted_words:
    print(word)

The sorted words are:
an
cased
example
hello
is
letters
this
with


# Write a Python Program to Remove Punctuation From a String?

In [7]:
import re

# Define an original string 
my_str = "sagarS for geEks!"

# Define a regular expression pattern for punctuations 
pattern = r'[^\w\s]'

# Use re.sub() function to replace all punctuations with an empty string 
no_punct = re.sub(pattern, '', my_str)

# Print the unpunctuated string 
print(no_punct)

sagarS for geEks
